name: Update README Stats (manual)

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update stats section in README
        run: |
          echo "Updating stats section..."
          
          # Build the new stats block
          STATS_BLOCK="<!--START_STATS-->\n"
          STATS_BLOCK+="![GitHub Stats](https://github-readme-stats.vercel.app/api?username=wporta&show_icons=true&locale=en)\n\n"
          STATS_BLOCK+="![GitHub Streak](https://github-readme-streak-stats.herokuapp.com/?user=wporta)\n\n"
          STATS_BLOCK+="![Top Languages](https://github-readme-stats.vercel.app/api/top-langs?username=wporta&show_icons=true&locale=en&layout=compact)\n\n"
          STATS_BLOCK+="[![Trophies](https://github-profile-trophy.vercel.app/?username=wporta)](https://github.com/ryo-ma/github-profile-trophy)\n"
          STATS_BLOCK+="<!--END_STATS-->"

          # Replace the section between markers
          awk -v stats="$STATS_BLOCK" '
            BEGIN { split(stats, lines, "\n") }
            /<!--START_STATS-->/ { print; for (i in lines) print lines[i]; skip=1; next }
            /<!--END_STATS-->/ { skip=0; next }
            !skip
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update GitHub stats section"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
