name: Update README Stats (manual)

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update stats section in README
        run: |
          NEW_STATS=$(cat <<EOF
![GitHub Stats](https://github-readme-stats.vercel.app/api?username=wporta&show_icons=true&locale=en)

![GitHub Streak](https://github-readme-streak-stats.herokuapp.com/?user=wporta)

![Top Languages](https://github-readme-stats.vercel.app/api/top-langs?username=wporta&show_icons=true&locale=en&layout=compact)

[![Trophies](https://github-profile-trophy.vercel.app/?username=wporta)](https://github.com/ryo-ma/github-profile-trophy)
EOF
          )
          awk '/<!--START_STATS-->/ { print; print ENVIRON["NEW_STATS"]; skip=1; next }
               /<!--END_STATS-->/ { skip=0 }
               !skip' README.md > README.tmp && mv README.tmp README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update GitHub stats section" || echo "No changes"
          git push
